/* Baker School of Aeronautics (2022) oral bank add-on. */
(()=>{
'use strict';
const bakerBanks=window.BAKER_ORAL_BANKS||[];
if(!bakerBanks.length)return;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const sectionLabel=s=>s[0].toUpperCase()+s.slice(1);
const grader=window.FAA_GRADER||null;
const logger=window.ORAL_LOGGER||null;
const totalBaker=bakerBanks.reduce((n,b)=>n+b.questions.length,0);
const totalOriginal=(window.ORAL_BANKS||[]).reduce((n,b)=>n+(b.questions?.length||0),0);
const totalAsa=(window.ASA_ORAL_BANKS||[]).reduce((n,b)=>n+(b.questions?.length||0),0);
function cleanStudentUi(){document.querySelectorAll('#testLogger,.logger-tools,.ai-badge').forEach(el=>el.style.setProperty('display','none','important'));document.querySelectorAll('button').forEach(el=>{if(el.textContent.trim()==='Test Answer Logger')el.style.setProperty('display','none','important')});document.querySelectorAll('span,small,p,div').forEach(el=>{if(el.children.length===0&&/Jeppesen-only local concept grader\s*v?[\d.]+/i.test(el.textContent||''))el.style.setProperty('display','none','important')})}
function updateHomeCount(){
  const home=$('sections');
  if(!home?.classList.contains('active')) return;
  const currentAsa=(window.ASA_ORAL_BANKS||[]).reduce((n,b)=>n+(b.questions?.length||0),0);
  const label='Question Banks';
  const value=(totalOriginal+currentAsa+totalBaker).toLocaleString()+' Questions';
  if($('headLabel') && $('headLabel').textContent!==label) $('headLabel').textContent=label;
  if($('headStat') && $('headStat').textContent!==value) $('headStat').textContent=value;
}
cleanStudentUi();
const homeScreen=$('sections');
if(homeScreen){
  new MutationObserver(()=>{
    if(homeScreen.classList.contains('active')){
      cleanStudentUi();
      updateHomeCount();
    }
  }).observe(homeScreen,{attributes:true,attributeFilter:['class']});
}
const style=document.createElement('style');style.textContent=`#testLogger,.logger-tools,.ai-badge{display:none!important}.baker-source-block{margin-top:30px;padding-top:24px;border-top:3px solid var(--navy,#14213d)}.baker-source-head{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;flex-wrap:wrap;margin-bottom:14px}.baker-source-kicker{font-weight:800;letter-spacing:.09em;text-transform:uppercase;color:#7c3aed;font-size:.78rem}.baker-card{border-color:#c4b5fd;background:linear-gradient(145deg,#f5f3ff,#fff)}.baker-card:hover,.baker-card:focus{border-color:#7c3aed;background:#ede9fe}.baker-badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#ede9fe;color:#5b21b6;font-size:.76rem;font-weight:800}.baker-feedback{display:none;padding:16px;border-radius:12px;margin-top:14px}.baker-feedback.show{display:block}.baker-feedback.pass{background:#dcfce7}.baker-feedback.almost{background:#fef3c7}.baker-feedback.fail{background:#fee2e2}.baker-expected{background:#fff;border-left:4px solid #7c3aed;padding:11px;margin-top:10px}`;document.head.appendChild(style);
const homeGrid=$('sectionGrid');if(!homeGrid)return;
const block=document.createElement('div');block.className='baker-source-block';block.innerHTML=`<div class="baker-source-head"><div><div class="baker-source-kicker">Additional source bank</div><h2 class="title" style="margin-top:4px">Baker School Oral Guide</h2><p class="subtitle" style="margin-bottom:0">Baker questions are kept separate from the Jeppesen and Dale Crane / ASA banks.</p></div><span class="baker-badge">${totalBaker.toLocaleString()} questions</span></div><div id="bakerSectionGrid" class="grid"></div>`;
const asaBlock=document.querySelector('.asa-source-block');(asaBlock||homeGrid).insertAdjacentElement('afterend',block);
const main=document.querySelector('main');main.insertAdjacentHTML('beforeend',`
<section id="bakerBanksScreen" class="screen"><div class="row"><button class="btn secondary" id="bakerBackHome">← Sections</button></div><div class="baker-source-kicker">Baker School Oral Guide</div><h2 id="bakerBanksTitle" class="title"></h2><p class="subtitle">Choose a subject or a mixed examination.</p><div id="bakerBankGrid" class="grid"></div></section>
<section id="bakerModesScreen" class="screen"><div class="row"><button class="btn secondary" id="bakerBackBanks">← Baker Subjects</button></div><div class="baker-source-kicker">Baker School Oral Guide</div><h2 id="bakerModeTitle" class="title"></h2><p class="subtitle">Choose how much of this bank to study.</p><div id="bakerModeGrid" class="grid"></div></section>
<section id="bakerExamScreen" class="screen"><div class="meta"><span id="bakerQNum"></span><span id="bakerModeLabel"></span></div><div class="question"><div class="baker-source-kicker">Baker School Oral Guide</div><div id="bakerSubjectLabel" class="label"></div><h2 id="bakerQText"></h2></div><div class="row"><button class="btn secondary" id="bakerSpeak">🔊 Read Question</button><button class="btn primary" id="bakerListen">🎤 Start Answer</button><button class="btn danger" id="bakerStop" disabled>■ Stop</button></div><div class="status" id="bakerStatus"><span class="dot"></span><span id="bakerStatusText">Begin when ready.</span></div><label for="bakerAnswer">Your answer transcript</label><textarea id="bakerAnswer" placeholder="Your spoken answer appears here. You may correct or type it."></textarea><p class="small">Review the transcript before submitting; technical terms can be misheard.</p><div class="row"><button class="btn success" id="bakerSubmit">Submit Answer</button><button class="btn secondary" id="bakerClear">Clear</button></div><div id="bakerFeedback" class="baker-feedback"><h3 id="bakerFbTitle"></h3><p id="bakerFbSummary"></p><div id="bakerConcepts" class="concepts"></div><div id="bakerExpected" class="baker-expected"></div></div><div class="row"><button class="btn primary" id="bakerNext" disabled>Next Question</button><button class="btn secondary" id="bakerExit">Exit</button></div></section>
<section id="bakerResultsScreen" class="screen"><div id="bakerBanner" class="banner"><h2 id="bakerResultTitle"></h2><p id="bakerResultSummary"></p></div><div id="bakerSubjectResults"></div><h2 class="title" style="font-size:1.25rem">Missed Questions</h2><div id="bakerReviews"></div><div class="row"><button class="btn primary" id="bakerAgain">Practice Again</button><button class="btn secondary" id="bakerResultsHome">Return Home</button></div></section>`);
let selectedSection=null,selectedBank=null,mode=null,questions=[],idx=0,answers=[],pending=null,last=null,recognition=null,listening=false,finalText='',attemptCounts={};const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
function show(id){document.querySelectorAll('main .screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function home(){speechSynthesis.cancel();if(listening&&recognition)try{recognition.stop()}catch{};show('sections');if($('headSub'))$('headSub').textContent='Choose a section';updateHomeCount()}
function tagged(q,b){return {...q,bankTitle:b.title,bankKey:b.key,section:b.section}}
function renderHomeCards(){const g=$('bakerSectionGrid');g.innerHTML='';['general','airframe','powerplant'].forEach(s=>{const bs=bakerBanks.filter(b=>b.section===s),count=bs.reduce((n,b)=>n+b.questions.length,0),btn=document.createElement('button');btn.className='cardbtn baker-card';btn.innerHTML=`<strong>${sectionLabel(s)}</strong><span>${bs.length} subjects • ${count} questions</span>`;btn.onclick=()=>renderBanks(s);g.appendChild(btn)})}
function renderBanks(s){selectedSection=s;$('bakerBanksTitle').textContent=`Baker ${sectionLabel(s)}`;const g=$('bakerBankGrid');g.innerHTML='';bakerBanks.filter(b=>b.section===s).forEach(b=>{const btn=document.createElement('button');btn.className='cardbtn baker-card';btn.innerHTML=`<strong>${esc(b.title)}</strong><span>${b.questions.length} questions</span>`;btn.onclick=()=>renderModes(b);g.appendChild(btn)});const mix=document.createElement('button');mix.className='cardbtn mixed';mix.innerHTML=`<strong>Mixed Baker ${sectionLabel(s)} Exam</strong><span>4 questions from every subject; 3 of 4 required in each subject</span>`;mix.onclick=()=>startMixed();g.appendChild(mix);if($('headSub'))$('headSub').textContent=`Baker ${sectionLabel(s)} oral practice`;show('bakerBanksScreen')}
function renderModes(b){selectedBank=b;$('bakerModeTitle').textContent=b.title;const g=$('bakerModeGrid');g.innerHTML='';[['practice','Practice','10 random questions with immediate feedback'],['complete','Complete',`Every question in this subject (${b.questions.length})`]].forEach(([m,t,sub])=>{const btn=document.createElement('button');btn.className='cardbtn baker-card';btn.innerHTML=`<strong>${t}</strong><span>${sub}</span>`;btn.onclick=()=>startSingle(m);g.appendChild(btn)});show('bakerModesScreen')}
function startSingle(m){mode=m;questions=shuffle(selectedBank.questions).slice(0,m==='practice'?10:selectedBank.questions.length).map(q=>tagged(q,selectedBank));last={kind:'single',section:selectedSection,bankKey:selectedBank.key,mode:m};start()}
function startMixed(){mode='mixed';const bs=bakerBanks.filter(b=>b.section===selectedSection);questions=shuffle(bs.flatMap(b=>shuffle(b.questions).slice(0,4).map(q=>tagged(q,b))));last={kind:'mixed',section:selectedSection};start()}
function start(){idx=0;answers=[];pending=null;attemptCounts={};if(logger?.startQuiz)try{logger.startQuiz({section:selectedSection,mode:`baker-${mode}`,bankKey:selectedBank?.key||'baker-mixed',bankTitle:selectedBank?.title||'Baker mixed',questionCount:questions.length,source:'Baker 2022'})}catch{};show('bakerExamScreen');load()}
function setStatus(t,on=false){$('bakerStatusText').textContent=t;$('bakerStatus').classList.toggle('listening',on)}
function load(){const q=questions[idx];$('bakerQNum').textContent=`Question ${idx+1} of ${questions.length}`;$('bakerModeLabel').textContent=mode==='mixed'?`Mixed Baker ${sectionLabel(selectedSection)}`:mode==='practice'?'Practice':'Complete';$('bakerSubjectLabel').textContent=q.bankTitle;$('bakerQText').textContent=q.question;$('bakerAnswer').value='';finalText='';pending=null;$('bakerFeedback').className='baker-feedback';$('bakerSubmit').disabled=false;$('bakerSubmit').textContent='Submit Answer';$('bakerNext').disabled=true;if($('headStat'))$('headStat').textContent=`${idx+1} / ${questions.length}`;if($('bar'))$('bar').style.width=`${idx/questions.length*100}%`;setStatus('Begin when ready.')}
function speak(){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(questions[idx].question);u.rate=.9;u.onstart=()=>setStatus('Reading the question aloud.');u.onend=()=>setStatus('Question complete. Begin your answer.');speechSynthesis.speak(u)}
if(SR){recognition=new SR();recognition.lang='en-US';recognition.continuous=true;recognition.interimResults=true;recognition.onstart=()=>{listening=true;$('bakerListen').disabled=true;$('bakerStop').disabled=false;setStatus('Listening…',true)};recognition.onresult=e=>{let interim='',fresh='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)fresh+=e.results[i][0].transcript+' ';else interim+=e.results[i][0].transcript}finalText+=fresh;$('bakerAnswer').value=(finalText+interim).trim()};recognition.onerror=e=>setStatus('Microphone error: '+e.error+'. You may type your answer.');recognition.onend=()=>{listening=false;$('bakerListen').disabled=false;$('bakerStop').disabled=true;setStatus($('bakerAnswer').value?'Answer captured. Review and submit.':'Listening stopped.')}}
function fallbackGrade(q,a){const norm=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),want=norm(q.idealAnswer).split(' ').filter(w=>w.length>3),got=new Set(norm(a).split(' ')),count=want.filter(w=>got.has(w)).length,passed=count>=Math.max(1,Math.ceil(want.length*.35));return {level:passed?'pass':count?'almost':'fail',passed,count,total:1,required:1,concepts:[{label:'Core answer idea',met:passed}]}}
function showFeedback(g,q){const cls=g.level==='pass'?'pass':g.level==='almost'?'almost':'fail';$('bakerFeedback').className='baker-feedback show '+cls;$('bakerFbTitle').textContent=g.level==='pass'?'PASS':g.level==='almost'?'ALMOST THERE':'TRY AGAIN';$('bakerFbSummary').textContent=`Recognized ${g.count} of ${g.total} key ideas; ${g.required} required to pass.`;$('bakerConcepts').innerHTML=(g.concepts||[]).map(c=>`<div class="concept ${c.met?'ok':'missing'}">${c.met?'✓ Recognized':'✗ Missing'}: ${esc(c.label)}</div>`).join('');$('bakerExpected').innerHTML=`<strong>Expected answer:</strong> ${esc(q.idealAnswer)}`}
function logAttempt(q,a,g){if(!logger?.recordAttempt)return;attemptCounts[q.id]=(attemptCounts[q.id]||0)+1;Promise.resolve(logger.recordAttempt({questionNumber:idx+1,attemptNumber:attemptCounts[q.id],section:q.section,bankKey:q.bankKey,bankTitle:q.bankTitle,questionId:q.id,question:q.question,studentResponse:a,expectedAnswer:q.idealAnswer,localLevel:g.level,localPassed:g.passed,recognizedConcepts:(g.concepts||[]).filter(c=>c.met).map(c=>c.label),missingConcepts:(g.concepts||[]).filter(c=>!c.met).map(c=>c.label),graderVersion:grader?.version||'fallback',reviewRecommended:g.reviewRecommended,sourceBank:'Baker 2022'})).catch(()=>{})}
function submit(){const a=$('bakerAnswer').value.trim();if(!a)return setStatus('Give an answer before submitting.');if(listening&&recognition)recognition.stop();$('bakerSubmit').disabled=true;const q=questions[idx],g=grader?.grade?grader.grade(q,a):fallbackGrade(q,a);pending={q,a,...g};$('bakerNext').disabled=false;logAttempt(q,a,g);if(mode==='mixed'){setStatus('Answer recorded. Results will be shown at the end.');return}showFeedback(g,q);if(g.passed)setStatus('Answer passed. Continue when ready.');else{$('bakerSubmit').disabled=false;$('bakerSubmit').textContent='Resubmit Answer';setStatus(g.level==='almost'?'Add the missing idea and resubmit, or continue when ready.':'Edit or add to your answer and try again, or continue when ready.')}}
function next(){if(!pending)return;answers.push(pending);pending=null;if(idx<questions.length-1){idx++;load();speak()}else finish()}
function finish(){if($('bar'))$('bar').style.width='100%';const correct=answers.filter(a=>a.passed).length;let pass=false;if(mode==='mixed'){const grouped={};answers.forEach(a=>{grouped[a.q.bankKey]??={title:a.q.bankTitle,total:0,correct:0};grouped[a.q.bankKey].total++;if(a.passed)grouped[a.q.bankKey].correct++});const rows=Object.values(grouped);pass=rows.every(r=>r.correct>=3);$('bakerSubjectResults').innerHTML=`<table><thead><tr><th>Subject</th><th>Score</th><th>Result</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.title)}</td><td>${r.correct} / ${r.total}</td><td><strong>${r.correct>=3?'PASS':'FAIL'}</strong></td></tr>`).join('')}</tbody></table>`;$('bakerResultSummary').textContent=pass?'Every subject met the required 3 of 4.':'One or more subjects scored below 3 of 4.'}else{pass=correct===answers.length;$('bakerSubjectResults').innerHTML='';$('bakerResultSummary').textContent=`You answered ${correct} of ${answers.length} correctly.`}$('bakerBanner').className='banner '+(pass?'pass':'fail');$('bakerResultTitle').textContent=pass?'PASS':'REVIEW RECOMMENDED';const missed=answers.filter(a=>!a.passed);$('bakerReviews').innerHTML=missed.length?missed.map(a=>`<div class="review"><strong>${esc(a.q.bankTitle)}</strong><p><b>Question:</b> ${esc(a.q.question)}</p><p><b>Your answer:</b> ${esc(a.a)}</p><p><b>Expected:</b> ${esc(a.q.idealAnswer)}</p></div>`).join(''):'<p>No missed questions.</p>';if($('headStat'))$('headStat').textContent=`${correct} / ${answers.length}`;show('bakerResultsScreen')}
function repeat(){if(!last)return home();if(last.kind==='mixed'){renderBanks(last.section);startMixed()}else{selectedSection=last.section;selectedBank=bakerBanks.find(b=>b.key===last.bankKey);startSingle(last.mode)}}
$('bakerBackHome').onclick=home;$('bakerBackBanks').onclick=()=>renderBanks(selectedSection);$('bakerSpeak').onclick=speak;$('bakerListen').onclick=()=>{if(!recognition)return setStatus('Speech recognition is unavailable. Type your answer.');finalText=$('bakerAnswer').value?$('bakerAnswer').value+' ':'';recognition.start()};$('bakerStop').onclick=()=>recognition&&recognition.stop();$('bakerSubmit').onclick=submit;$('bakerClear').onclick=()=>{$('bakerAnswer').value='';finalText=''};$('bakerNext').onclick=next;$('bakerExit').onclick=home;$('bakerResultsHome').onclick=home;$('bakerAgain').onclick=repeat;
renderHomeCards();updateHomeCount();
})();
